Feature/organization
SoftBox-CPS/BackendMVC pull request #13
Opened 2022-09-07 14:01 UTC by Zenobiam

2022-09-09 05:42 UTC, Tiozafrem requested changes
Как проверялась работоспособность добавленных функций? У меня ошибка вылезает при любом запросе на организацию, потому что не зарегистрирована зависимость

2022-09-09 05:42 UTC, Tiozafrem commented on SoftBox.DataBase/Entities/UserOrganization.cs
> +        StartDateTimeOffset = DateTimeOffset.Now;
Какой смысл этих изменений?

2022-09-09 05:42 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +        private readonly DbRepository<Organization, Guid> _dbOrgRepository;
Почему такой стиль именования? В проекте не используется символ _

2022-09-09 05:42 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +    public class OrganizationController : Base.ViewController
Почему наследование от этого класса, а не от класса с моделью?

2022-09-09 05:42 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +        public OrganizationController(DbRepository<Organization, Guid> dbOrgRepository,
Точно работает? Эта зависимость была зарегистрирована?

2022-09-09 05:42 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +        public IActionResult Registration()
Почему тут не указан путь?

2022-09-09 05:42 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +                UserOrganizations = organization.UserOrganizations,
Как ты будешь создавать список продукции без создания организации?

2022-09-09 05:42 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +                StartDateTimeOffset = DateTime.UtcNow,
Почему тут используется тип данных отличный от поля? Это поле заполняется в конструкторе

2022-09-09 05:42 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +            if (await _dbOrgRepository.ExistById(id))
Получается, ты разрешаешь удалять организацию другого пользователя?

2022-09-09 05:42 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +            /// TODO отвязать от пользователя
Пользователя надо отвязывать до удаления организации, иначе ошибка.

2022-09-09 05:42 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +            // Добавление самой организации
Какой смысл этого комментария и остальных?

2022-09-09 05:42 UTC, Tiozafrem commented on web/appsettings.json
> +    "SoftBoxMS": "Data Source=(localdb)\\MSSQLLocalDB;Database=SoftboxDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnet
Зачем каждый раз переписывать файл под себя? Необходимо использовать секреты

2022-09-09 05:42 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +        //public async Task<IActionResult> ChangeUser(Guid id, [FromBody] UserOrganization uOrganization)
Нельзя методы комментировать. Не надо - удали

2022-10-23 14:07 UTC, Tiozafrem requested changes
Код точно работает? Добавление организации отрабатывает во всех случаях?

2022-10-23 14:07 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +                OrganizationId = organization.Id,
Чему у тебя равен Id, если этот параметр инициализируется только после записи в СУБД, если делать через связь, то инициализировать это значение не нужно

2022-10-23 14:07 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +           return await Add(new Organization
Уверен что нужно создавать метод, который вернёт весь новый объект? В других методах добавления это реализовано иначе

2022-10-23 14:07 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +    [HttpGet("\"{organizationId:Guid}/GetOrganizationById\"")]
Что тут написано?

2022-10-23 14:07 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +    public async Task<IActionResult> GetOrganizationById(Guid organizationId)
Чем этот метод отличается от стандартного в базовом классе?

2022-10-23 14:07 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +    public async Task<IActionResult> GetAllOrganizations()
Чем этот метод отличается от стандартного в базовом классе?

2022-10-23 14:07 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +    [HttpGet]
Пустые пути лучше не оставлять, хотя бы / написать

2022-10-23 14:07 UTC, Tiozafrem commented on web/appsettings.json
> -    "SoftBoxMS": "Server=localhost, 1433;Database=SoftBox;User=SA;Password=Super909!;MultipleActiveResultSets=True"
Какой смысл этих изменений? Зачем это переписывать это каждый раз под себя? При добавление commit необходимо выбирать только файлы, которые должны быть затронуты для работы, а не для своей конфигурации. И лучше использовать секреты для соединения с базой данных

2022-11-26 14:50 UTC, Zenobiam commented on SoftBox.DataBase/InterfacesRepository/IOrganizationRepository.cs
> +        public Task<Organization> GetByNameAsync(string name);
выдает ошибку при использовании стандартных репозиториев типа "INamedRepository"

2022-11-28 10:53 UTC, Tiozafrem requested changes

2022-11-28 10:53 UTC, Tiozafrem commented on SoftBox.DataBase/Repository/OrganizationRepository.cs
> +    public async Task<Organization> GetByIdAsync(Guid id)
Зачем нужны эти методы, если они только вызывают базовый класс? Может тогда вместо них сразу вызывать методы в базовом классе

2022-11-28 10:53 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +    public async Task<IActionResult> CreateOrganization([FromBody] Organization organization)
Что будет, если человек уже находиться в организации? Это необходимо предусмотреть. Либо запретить это действие, либо прекратить членство в старой организации?

2022-12-26 18:33 UTC, Zenobiam commented on web/Controllers/OrganizationController.cs
> +        var userOrg = organizationRepository.ExistUserOrganizationUser(UserId);
добавил

2022-12-26 18:33 UTC, Zenobiam commented on SoftBox.DataBase/InterfacesRepository/IOrganizationRepository.cs
> +    public Task<Organization> GetByNameAsync(string name);
убрал, переписал репозиторий

2022-12-26 18:34 UTC, Zenobiam commented
пофиксил ошибку с подключением репозитория, я его дважды пытался подрубать и он ругался

2022-12-27 19:10 UTC, Tiozafrem approved these changes

2022-12-27 19:12 UTC, merged