Main feature/product
SoftBox-CPS/BackendMVC pull request #15
Opened 2022-09-16 16:10 UTC by CrlnProgramming

New features added, bugs fixed.
Can go drink tea...

2022-09-16 17:37 UTC, Tiozafrem requested changes
Уже лучше, требуются доработки

2022-09-16 17:37 UTC, Tiozafrem commented on SoftBox.DataBase/Entities/Product.cs
> +        ErrorMessage = "Value for {0} must be between {1} and {2}")]
Какой смысл этих изменений, если данное поле инициализирует в конструкторе

2022-09-16 17:37 UTC, Tiozafrem commented on SoftBox.DataBase/InterfacesRepository/IProductRepository.cs
> +    public Task<Organization> GetOrganizationByUserId(string organizationId);
Принимаемый аргумент точно должен так называться?

2022-09-16 17:37 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +    [HttpPost("PostProductByOrganizationName")]
Почему пост? Зачем такое путь?

2022-09-16 17:37 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +        if (String.IsNullOrEmpty(product.Id.ToString()))
Зачем брать ид с клиента? Он автоматически создаётся при записи в базу

2022-09-16 17:37 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +        var products = await productRepository.GetOrganizationByUserId(product.Id.ToString());
Получил организацию и дальше что?

2022-09-16 17:37 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +            return await Add(product);
А организация где получается?

2022-09-16 19:09 UTC, CrlnProgramming commented on SoftBox.DataBase/InterfacesRepository/IProductRepository.cs
> +    public Task<Organization> GetOrganizationByUserId(string organizationId);
Да, изменю

2022-09-16 20:43 UTC, CrlnProgramming commented on web/Controllers/ProductController.cs
> +        if (String.IsNullOrEmpty(product.Id.ToString()))
убрал

2022-09-19 13:55 UTC, CrlnProgramming commented on SoftBox.DataBase/Entities/Product.cs
> +        ErrorMessage = "Value for {0} must be between {1} and {2}")]
Убрал

2022-10-23 14:19 UTC, Tiozafrem requested changes
Код точно работает? В сваггере нет лишней информации?

2022-10-23 14:19 UTC, Tiozafrem commented on SoftBox.DataBase/Entities/Product.cs
> -    [JsonIgnore]
Зачем отсюда убирать эти аннотации?

2022-10-23 14:19 UTC, Tiozafrem commented on SoftBox.DataBase/Repository/ProductRepository.cs
> +            .ToArrayAsync();
Почему возвращать тут массив, а не стандартный лист?

2022-10-23 14:19 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +[Route("api/[controller]")]
Зачем тут приписка api? В другой части проекта этого нет

2022-10-23 14:19 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +    [HttpGet("ProductByOrganizationName/{organizationName}")]
Зачем такое длинное название в пути?

2022-10-23 14:19 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +            ModelState.AddModelError("Customer", "Not found organization");
Зачем тут такая ошибка? Какой смысл этого, если у тебя после это не проверяется? Тут можно сразу вернуть 404

2022-10-23 14:19 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +        if (foundOrganizatinonUser != null)
Зачем продолжение работы писать в условии? Не лучше проверить на обратный случай и при положительном исходе вернуть 400?

2022-10-23 14:19 UTC, Tiozafrem commented on web/MVCWebApplication.csproj
> +	<ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>
Какой смысл этих изменений?

2022-10-23 14:19 UTC, Tiozafrem commented on web/Properties/serviceDependencies.json
> +{
Какой смысл этого файла?

2022-10-23 14:19 UTC, Tiozafrem commented on web/Properties/serviceDependencies.local.json
> +{
Какой смысл этого файла?

2022-10-23 14:19 UTC, Tiozafrem commented on web/appsettings.json
> +
Какой смысл этих изменений?

2022-10-30 14:26 UTC, CrlnProgramming commented on web/Controllers/ProductController.cs
> +        if (foundOrganizatinonUser != null)
Так?
public async Task<IActionResult> CreateProduct([FromBody] Product product)
    {
        var foundOrganizatinonUser = await productRepository.GetOrganizationByUserId(User.Claims.First(x => x.Type == "id").Value);
        if (foundOrganizatinonUser == null)
            return BadRequest();

        var addProductItem = new Product()
        {
            Name = product.Name,
            OrganizationId = foundOrganizatinonUser.Id,
            Price = product.Price,
            ImageUrl = product.ImageUrl
        };
        return await Add(addProductItem);
    }

2022-11-25 21:08 UTC, Tiozafrem requested changes
Остались мелкие правки.

2022-11-25 21:08 UTC, Tiozafrem commented on SoftBox.DataBase/Repository/ProductRepository.cs
> +    public async Task<Organization> GetOrganizationByUserId(string userOrganizationId)
Тут имя параметра должно быть userId

2022-11-25 21:08 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +    public async Task<IActionResult> FindProductByOrganizationName(string organizationName)
Нет 200 возвращаемого кода в аннотациях

2022-11-25 21:08 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +    public async Task<IActionResult> CreateProduct([FromBody] Product product)
В этом методе нет проверки на валидность модели. А это значит что добавления проверки на значение величины цены в модели не имело смысла. Лучше сюда добавить проверку или проверку вместе с dto

2022-11-25 21:08 UTC, Tiozafrem commented on web/MVCWebApplication.csproj
> +	<ItemGroup>
Зачем здесь это?

2022-11-25 21:08 UTC, Tiozafrem commented on web/Properties/serviceDependencies.json
> +{
А файл так и не удалил

2022-12-19 14:26 UTC, Tiozafrem requested changes

2022-12-19 14:26 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +            ModelState.AddModelError("CreateProduct", "Только пользователи организации могут создавать продукты");
Если добавлять ошибку, то после необходимо проверить валидность модели. Факт добавления ошибки не прерывает выполнения кода

2022-12-27 18:20 UTC, Tiozafrem approved these changes

2022-12-27 18:22 UTC, merged