Origin/feature/room
SoftBox-CPS/BackendMVC pull request #17
Opened 2022-11-13 18:36 UTC by A-haMoment

Feature/Room by Igor Osavoluk

2022-11-16 18:02 UTC, Tiozafrem requested changes
Если изменилась модель, тогда где миграция?

2022-11-16 18:02 UTC, Tiozafrem commented on SoftBox.DataBase/Repository/RoomRepository.cs
> +        item.PeriodPaymentStatus = new PeriodPaymentStatus { Id = 1, Name = "PeriodPaymentStatusTest1" };//тут надо определиться, какие статусы у Периода оплаты и какие номера каждый из статусов имее
Что будет если у нас в периоде не будет/уже будет такая запись? Если там будет другое имя?

2022-11-16 18:02 UTC, Tiozafrem commented on SoftBox.DataBase/Repository/RoomRepository.cs
> +        if (roomUser is null)
А как может быть это значение не пустым, если изначально пользователь не присоединен к комнате и такой записи не существует?

2022-11-17 12:17 UTC, A-haMoment commented on SoftBox.DataBase/Repository/RoomRepository.cs
> +        if (roomUser is null)
Да,я неправильно использовал метод GetRoomUserByRoomIdUserId.
Я так понимаю, что переделать нужно так :
-переделать параметры метода - PinCustomerToRoom(Guid roomId, Guid userId)
-убрать метод GetRoomUserByRoomIdUserId - он здесь ни к чему.
- нужно внутри метода PinCustomerToRoom - создавать RoomUser с параметрами userId, roomId и т.п., и по сути, уже этого RoomUser нужно добавлять к item.RoomUsers.
Вся загвоздка только в том,что для того,чтобы создать RoomUser'a - нужно будет использовать RoomUserRepository ( которого ,во-первых, нет, во-вторых,  получается в одном репозитории RoomRepository связанный запрос, где нужно и update'ить Room и создавать RoomUser'a)
Как ты смотришь на такую идею?

2022-11-17 12:22 UTC, A-haMoment commented on SoftBox.DataBase/Repository/RoomRepository.cs
> +        item.PeriodPaymentStatus = new PeriodPaymentStatus { Id = 1, Name = "PeriodPaymentStatusTest1" };//тут надо определиться, какие статусы у Периода оплаты и какие номера каждый из статусов имее
вообще говоря, я эту запись "item.PeriodPaymentStatus = new PeriodPaymentStatus { Id = 1, Name = "PeriodPaymentStatusTest1" };" создал для того,чтобы заставить работать этот метод, т.к. вначале у меня не было никаких данных => я хоть какие-то данные добавляю.

Лучше всего ( и легче всего) мне кажется переделать так, чтобы определенный PeriodPaymentStatus уже передавался сразу же в параметрах метода CreatePaymentPeriod() и собственно этот PeriodPaymentStatus уже присваивать.

Как ты думаешь?

2022-11-17 12:28 UTC, A-haMoment commented on SoftBox.DataBase/Repository/RoomRepository.cs
> +        _ = await SaveChanges(cancel).ConfigureAwait(false);
Два вопроса :
- т.е. я так понимаю, что свойство RoomStatusId в классе Room нужно убрать совсем?
- а что еще добавить в метод CreateRoomWithStatus ? Чего не хватает? Мы вроде добавляем Рум в список Румов. Может я что-то упускаю?

2022-11-17 12:30 UTC, A-haMoment commented on SoftBox.DataBase/Repository/HoldRepository.cs
> +        item.HoldStatus = new HoldStatus { Id = 2 };
Да, я думаю, ты прав .
Пофиксить все подобные свойства в Руме и Холде и всех остальных - заменить на id?

2022-11-17 12:32 UTC, A-haMoment commented on SoftBox.DataBase/Repository/HoldRepository.cs
> +    /// <param name="holdId"></param>
Да, осталось с прошлой итерации изменения. Уберу

2022-11-17 12:40 UTC, A-haMoment commented on SoftBox.DataBase/Repository/HoldRepository.cs
> +    public async Task CreateHoldWithStatus(HoldStatus status, CancellationToken cancel = default)
Я так понимаю,что вариантов работы с ним немного.
По сути, Холд сам у себя отслеживает прогресс ( насколько он достиг даты экспирации), плюс все,что мы можем с ним делать - это Сбросить прогресс и дату у него (я так понимаю, возобновив его), либо Закрыть его полностью, пометив холд выполненным.
Больше никаких других полезных способов и методов я пока не вижу.

2022-11-17 12:42 UTC, A-haMoment commented on SoftBox.DataBase/Repository/DatabaseInitializer.cs
> +public class DatabaseInitializer : IDatabaseInitializer
Да, я думаю, это выбивается из всей стилистики кода. Я использовал это, когда возился с тем, чтобы загрузить тестовые данные в БД . Мне нужен был знакомый код, который ранее работал и на основе него я понял,как добавить все тестовые данные.
Я удалю

2022-11-17 12:45 UTC, A-haMoment commented on SoftBox.DataBase/Repository/RoomStatusRepository.cs
> +    private SoftBoxDbContext dbcontext;
Удалю. Скописченный код

2022-11-17 13:34 UTC, A-haMoment commented on web/Controllers/RoomController.cs
> +    public async Task<IActionResult> CreateRoom(int amountProduct, DateTime holdExpirationDate)
Ты имеешь ввиду ,чтобы параметры передавались в json внутри body ?

2022-11-17 13:35 UTC, A-haMoment commented on web/Controllers/HoldController.cs
> +    private readonly IHoldStatusRepository holdStatusRepository;
Убрал

2022-11-17 13:38 UTC, A-haMoment commented on web/Views/Shared/_Layout.cshtml
> +    <form asp-action="PinCustomerToRoom" asp-controller="Room" asp-route-userId="FEFD723B-6F17-4FE8-B6EB-E13C042CC668" asp-route-roomId="F8985D9C-BEC1-4725-AAFB-8C33ED6FC12C" method="post">
Для тестирования я это и использовал, чтобы посмотреть,что все работает с данными из БД . Конечно, потом это все надо будет заменять на что-то более дельное.
Я могу вообще это вырезать : т.к. сейчас все работает + фронтенд отключен и подобная запись просто замусоривает код.

2022-11-17 13:39 UTC, A-haMoment commented on SoftBox.DataBase/Repository/IDatabaseInitializer.cs
> +public interface IDatabaseInitializer
Я имею ввиду класс DatabaseInitializer

2022-11-17 13:41 UTC, A-haMoment commented on SoftBox.DataBase/InterfacesRepository/IHoldRepository.cs
> +    public Task CreateHoldWithStatus(HoldStatus status, CancellationToken cancel = default);
Ну, можно заменить на возврат булевого значения . Только мне нужно знать, где конкретно нужно возвращать успешно/неуспешно . Только во всех методах в этом интерфейсе IHoldRepository? или где-то еще ?

2022-11-17 13:45 UTC, A-haMoment commented on SoftBox.DataBase/Entities/RoomList.cs
> +public class RoomList : EntityName<Guid>
Это , по сути, объединение двух концептов "История списка Румов на которых подписан покупатель в настоящее время"  и "История списка Румов на которых подписан продавец, по которым идут торги" . Мы это обсуждали с Ильей. Я предложил использовать один класс вместо двух. И реализовать функционал двух классов в одном .
Я не знаю,как с ними работать, т.к. это не обсуждалось. Пока реализован только CRUD для RoomListRepository.

Я предлагаю это лучше обсудить всем вместе .

2022-11-17 13:49 UTC, A-haMoment commented on SoftBox.DataBase/Entities/RoomCreationStatus.cs
> +﻿
Я не против. Создавая подобные классы статусы, я предположил,как бы это могло работать , одновременно соблюдая стилистику кода. 
Т.е. я правильно понимаю, что ты предлагаешь использовать RoomStatus , вместо всех эти RoomCreationStatus, PeriodPaymentStatus ?

2022-11-17 13:50 UTC, A-haMoment commented on SoftBox.DataBase/Entities/Hold.cs
> +    public int Progress { get; set; }//реализация прогресса холда. Как только достигает 100%,то холд завершается . Я предполагаю,что отсчитываться прогресс будет от ExpirationDate и сравниваться с те
Не знаю, не обсуждали в рамках ТЗ. Это было предложено мной в обсуждении с Ильей, но мы не прописывали, что конкретно должен делать этот класс, какие у него методы, логика и т.п. Пока это заготовка на будущее

2022-11-17 13:52 UTC, A-haMoment commented on SoftBox.DataBase/Entities/Hold.cs
> +    public bool IsActive { get; set; }
Не знаю,как будет лучше. Можно убрать HoldStatus и оставить свойство IsActive , или наоборот. 
Это вы мне скажите, как вам будет лучше.

2022-11-17 13:54 UTC, A-haMoment commented on SoftBox.DataBase/Entities/Hold.cs
> +    [Column("hold_status")]
Я думаю, как ты писал ранее, можно просто заменить это HoldStatus на id-шник ( типа holdStatusId) . Либо вообще убрать HoldStatus из класса Hold.
Но решать не мне.

2022-11-17 13:55 UTC, A-haMoment commented on web/Program.cs
> +//using Microsoft.Extensions.Options;
Я проверял некоторые вещи , комментируя и раскомментируя отдельные строки. Некоторые комменты так и остались

2022-11-17 13:56 UTC, A-haMoment commented on web/Program.cs
> +        options.SwaggerEndpoint("/swagger/v1/swagger.json", "v1");
хорошо удалю

2022-11-17 13:58 UTC, A-haMoment commented on web/Views/RoomList/Index.cshtml
> +                @foreach (RoomList rl in ViewBag.RoomList)
Старый код, который я использовался только для целей тестирования и вывода результатов, что получилось в том или ином случае. Больше у этого нет никаких иных причин

2022-11-17 14:01 UTC, A-haMoment commented on web/MVCWebApplication.csproj
> +		<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.4.0" />
этот удалил : <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.17.0" />
а вот эти: 
<PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
<PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.4.0" />
<PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.4.0" />

Это подключение Swagger в проект .

2022-11-17 14:04 UTC, A-haMoment commented on web/MVCWebApplication.csproj
> +	<ItemGroup>
Это ссылка на проект infrastructure/SoftBox.Database .
Если эту ссылку удалить, то проект web/MVCWebApplication не сможет пользоваться методами и классами из SoftBox.Database

2022-11-22 11:59 UTC, Tiozafrem requested changes

2022-11-22 11:59 UTC, Tiozafrem commented on SoftBox.DataBase/Entities/Hold.cs
> +    [Column("hold_status")]
Название колонки указывается только 1 раз в самом поле id, в навигационном свойстве указывать его не надо

2022-11-22 11:59 UTC, Tiozafrem commented on SoftBox.DataBase/Entities/Room.cs
> +    public RoomStatus RoomCreationStatus { get; set; }
Зачем нужно такое поле, которое не идёт в БД?

2022-11-22 11:59 UTC, Tiozafrem commented on SoftBox.DataBase/Entities/Room.cs
> +    public Hold Hold { get; set; }
А где сами поля, а не навигационные свойства?

2022-11-22 11:59 UTC, Tiozafrem commented on SoftBox.DataBase/Entities/Room.cs
> +    public bool IsActive { get; set; }
Мы же договорились без bool полей. Такие значения принимаются на основе статуса

2022-11-22 11:59 UTC, Tiozafrem commented on SoftBox.DataBase/InterfacesRepository/IHoldRepository.cs
> +    public Task<bool> CreateHoldWithStatus(HoldStatus status, CancellationToken cancel = default);
Если мы создаём холд, мы же должны на него перейти. Тут лучше возвращать сам холд, а не bool

2022-11-22 11:59 UTC, Tiozafrem commented on SoftBox.DataBase/InterfacesRepository/IHoldRepository.cs
> +    public Task<bool> ResetHold(Guid holdId, int holdStatusId, CancellationToken cancel = default);
Чем этот метод отличается от следующего?

2022-11-22 11:59 UTC, Tiozafrem commented on web/Controllers/RoomController.cs
> +        if (!String.IsNullOrEmpty(userId))
Зачем тут эта проверка? Почему пост метод доступен всем? Тут лучше сделать его доступным только авторизированным пользователям, тогда мы всегда сможем получить это значение.

2022-11-22 11:59 UTC, Tiozafrem commented on web/Controllers/HoldController.cs
> +public class HoldController : Controller
А создавать холд как?

2022-11-22 11:59 UTC, Tiozafrem commented on SoftBox.DataBase/Repository/RoomRepository.cs
> +        item.RoomUsers.Add(roomUser);
Зачем это действие нужно? Мы уже добавили значение в БД прошлым действием.

2022-11-22 11:59 UTC, Tiozafrem commented on SoftBox.DataBase/Repository/RoomRepository.cs
> +        item.PeriodPaymentStatus = new PeriodPaymentStatus { Id = 2, Name = "PeriodPaymentStatusTest2" };//тут надо определиться, какие статусы у Периода оплаты и какие номера каждый из статусов имее
Тут и в подобных местах мы не должны создавать новый статус.

2022-11-23 11:13 UTC, A-haMoment commented on SoftBox.DataBase/Entities/Room.cs
> +    public RoomStatus RoomCreationStatus { get; set; }
Если я ставлю свойство RoomCreationStatus , которое имеет тип RoomStatus  без атрибута [Not Mapped] , то у меня компилятор начинает ругаться на это, т.к. у нас уже у Room'a свойство RoomStatus имеющее тип RoomStatus . т.е. я так понимаю у нас два свойства имеют один и тот же тип RoomStatus.

2022-11-23 11:16 UTC, A-haMoment commented on SoftBox.DataBase/Entities/Room.cs
> +    public Hold Hold { get; set; }
что ты имеешь ввиду?

2022-11-23 11:17 UTC, A-haMoment commented on SoftBox.DataBase/Entities/Room.cs
> +    public bool IsActive { get; set; }
Я убрал поля IsActive и IsActiveTrading

2022-11-23 11:18 UTC, A-haMoment commented on SoftBox.DataBase/InterfacesRepository/IHoldRepository.cs
> +    public Task<bool> CreateHoldWithStatus(HoldStatus status, CancellationToken cancel = default);
хорошо, изменю

2022-11-23 11:20 UTC, A-haMoment commented on SoftBox.DataBase/InterfacesRepository/IHoldRepository.cs
> +    public Task<bool> ResetHold(Guid holdId, int holdStatusId, CancellationToken cancel = default);
ResetHold - это сбросить Холд. т.е. высчитывать прогресс в холде заново 
CompleteHold - завершить холд.
У них будут разные holdStatusId

2022-11-23 11:23 UTC, A-haMoment commented on web/Controllers/HoldController.cs
> +public class HoldController : Controller
Пока мы этот момент не обсуждали.

2022-11-23 11:24 UTC, A-haMoment commented on SoftBox.DataBase/Repository/RoomRepository.cs
> +        item.RoomUsers.Add(roomUser);
Ты про какое действие говоришь?
вот это :  _ = await dbcontext.RoomUsers.AddAsync(roomUser).ConfigureAwait(false); ?
или про это : item.RoomUsers.Add(roomUser); ?
Я из сообщения твоего понять не могу

2022-11-23 11:26 UTC, A-haMoment commented on SoftBox.DataBase/Repository/RoomRepository.cs
> +        item.PeriodPaymentStatus = new PeriodPaymentStatus { Id = 2, Name = "PeriodPaymentStatusTest2" };//тут надо определиться, какие статусы у Периода оплаты и какие номера каждый из статусов имее
пофиксил

2022-11-23 14:03 UTC, A-haMoment commented on SoftBox.DataBase/Entities/Hold.cs
> +    [Column("hold_status")]
public HoldStatus HoldStatus { get; set; }
это свойство вообще убрать ? Я немного не понял

2022-11-25 07:56 UTC, Tiozafrem commented on SoftBox.DataBase/InterfacesRepository/IHoldRepository.cs
> +    public Task<bool> ResetHold(Guid holdId, int holdStatusId, CancellationToken cancel = default);
Так если мы принимаем это как параметр, а не задаём в коде, зачем тогда два метода, которые могут делать одно и тоже?

2022-11-25 07:59 UTC, Tiozafrem commented on SoftBox.DataBase/Repository/RoomRepository.cs
> +        item.RoomUsers.Add(roomUser);
Про второе. Они имеют одинаковый функционал и вместе их использовать не имеет смысла

2022-11-25 08:01 UTC, Tiozafrem commented on SoftBox.DataBase/Entities/Room.cs
> +    public Hold Hold { get; set; }
Навигационные свойства - свойство, где храниться связующая запись с другой таблицей.
Поле о котором я говорю - отдельный id для связи с этой таблицей.

2022-11-25 08:05 UTC, Tiozafrem commented on SoftBox.DataBase/Entities/Room.cs
> +    public RoomStatus RoomCreationStatus { get; set; }
Надо разделить эти поля. Это можно сделать по аннотация или через метод создания модели в контексте

2022-11-25 08:12 UTC, Tiozafrem commented on SoftBox.DataBase/Entities/Hold.cs
> +    [Column("hold_status")]
HoldStatus навигационное свойство, HoldStatusId - поле, к которому должно быть привязано свойство.
Название атрибута должно быть только у одного из двух.

2022-11-26 14:16 UTC, A-haMoment commented on SoftBox.DataBase/Repository/RoomRepository.cs
> +        item.RoomUsers.Add(roomUser);
Хорошо. Второе действие уберу

2022-11-26 14:18 UTC, A-haMoment commented on SoftBox.DataBase/InterfacesRepository/IHoldRepository.cs
> +    public Task<bool> ResetHold(Guid holdId, int holdStatusId, CancellationToken cancel = default);
Ок, я уберу метод ResetHold

2022-11-27 20:05 UTC, A-haMoment commented on SoftBox.DataBase/Entities/Room.cs
> +    public RoomStatus RoomCreationStatus { get; set; }
прописал эти две строчки:
modelBuilder.Entity<Room>().HasOne(r => r.RoomStatus).WithOne();
modelBuilder.Entity<Room>().HasOne(r => r.RoomStatusCreation).WithOne();

Только с этим код нормально запускается. Все остальные варианты - не работают - компилятор ругается

2022-11-27 20:05 UTC, A-haMoment commented on SoftBox.DataBase/Entities/Room.cs
> +    public Hold Hold { get; set; }
добавил HoldId в модель Room

2022-11-28 07:40 UTC, Tiozafrem commented
Так если модель поменялась, почему нет миграции?

2022-11-30 21:23 UTC, Tiozafrem requested changes

2022-11-30 21:23 UTC, Tiozafrem commented on SoftBox.DataBase/Entities/Room.cs
> +    public Guid HoldId { get; set; }
Зачем это поле делать игнорируемым? Оно как раз должно приниматься при создание нового объекта

2022-11-30 21:23 UTC, Tiozafrem commented on SoftBox.DataBase/Entities/Room.cs
> +    //[Column("room_status_id")]
Название колонки зачем комментировать?

2022-11-30 21:23 UTC, Tiozafrem commented on SoftBox.DataBase/Migrations/20221128185924_FixRoomStatusProperties1.cs
> +        //migrationBuilder.DropForeignKey(
Зачем это всё комментировать в миграции? Зачем тогда такая миграция нужна? При откате такой миграции возникают проблемы, так как в откате он пробует удалить то, что не создалось

2022-11-30 21:23 UTC, Tiozafrem commented on SoftBox.DataBase/Migrations/20221128190241_FixRoomStatusProperties2.cs
> +    {
Зачем  нужна пустая миграция?

2022-11-30 21:23 UTC, Tiozafrem commented on SoftBox.DataBase/SoftBoxDbContext.cs
> +    public DbSet<RoomCreationStatus> RoomCreationStatuses { get; set; }
Так если пришли к реализации без отдельной таблицы для создания,  зачем  тогда она здесь нужна?

2022-11-30 21:23 UTC, Tiozafrem commented on web/Controllers/RoomController.cs
> +    private readonly IOrganizationRepository organizationRepository;
Зачем здесь эти репозитории, которые не используются?

2022-11-30 21:23 UTC, Tiozafrem commented on web/Controllers/RoomController.cs
> +            Room item = new Room
Этот код точно работает? У меня при тестирование постоянно ошибки из-за попытки создать новые навигационные поля

2022-11-30 21:23 UTC, Tiozafrem commented on web/Controllers/RoomController.cs
> +            _ = await roomRepository.Add(item);
Зачем вызывать базовый метод, если ты писал свой метод в репозитории?

2022-12-01 08:13 UTC, A-haMoment commented on SoftBox.DataBase/Entities/Room.cs
> +    //[Column("room_status_id")]
пофиксил

2022-12-01 08:18 UTC, A-haMoment commented on web/Controllers/RoomController.cs
> +    private readonly IOrganizationRepository organizationRepository;
пофиксил. Эти репозитории использовались для тестов

2022-12-01 17:54 UTC, A-haMoment commented on SoftBox.DataBase/Entities/Room.cs
> +    public Guid HoldId { get; set; }
пофиксил

2022-12-01 18:09 UTC, A-haMoment commented on SoftBox.DataBase/SoftBoxDbContext.cs
> +    public DbSet<RoomCreationStatus> RoomCreationStatuses { get; set; }
пофиксил

2022-12-06 08:26 UTC, Tiozafrem requested changes

2022-12-06 08:26 UTC, Tiozafrem commented on SoftBox.DataBase/Entities/Hold.cs
> +    public int HoldStatusId { get; set; }
Название колонки необходимо указывать только один раз. Сейчас она указана и в навигационном свойстве и в самой колонке.

2022-12-06 08:26 UTC, Tiozafrem commented on SoftBox.DataBase/SoftBoxDbContext.cs
> +        modelBuilder.Entity<PeriodPaymentStatus>().HasMany(r => r.Rooms).WithOne(r => r.PeriodPaymentStatus).HasForeignKey(r => r.PeriodPaymentStatusId).IsRequired();
Зачем это здесь описывать? Обычны описываем только через аннотации, к такому способу приходим только если это не получается реализовывать через аннотацию, как например с несколькими связями между одинаковыми таблицами. Тут можно обойтись аннотациями.

2022-12-06 08:26 UTC, Tiozafrem commented on web/Controllers/RoomController.cs
> +                Hold = room.Hold,
Зачем нам тут навигационное поле, если мы его даже не принимаем?

2022-12-06 13:28 UTC, A-haMoment commented on SoftBox.DataBase/Entities/Hold.cs
> +    public int HoldStatusId { get; set; }
Убрал [Column("hold_status_id")]

2022-12-06 13:30 UTC, A-haMoment commented on web/Controllers/RoomController.cs
> +                Hold = room.Hold,
Ты про что имеешь ввиду ?

2022-12-06 13:41 UTC, A-haMoment commented on SoftBox.DataBase/SoftBoxDbContext.cs
> +        modelBuilder.Entity<PeriodPaymentStatus>().HasMany(r => r.Rooms).WithOne(r => r.PeriodPaymentStatus).HasForeignKey(r => r.PeriodPaymentStatusId).IsRequired();
Убрал этот момент

2022-12-19 14:21 UTC, Tiozafrem requested changes

2022-12-19 14:21 UTC, Tiozafrem commented on web/Controllers/RoomController.cs
> +                _ = await roomRepository.CreateRoomWithStatus(room, room.RoomStatusId);
Тут лучше брать новый объект и перенаправлять уже на него, а не на список объектов.

2022-12-19 14:21 UTC, Tiozafrem commented on web/Controllers/RoomController.cs
> +        if (room != null)
Проверка модели уже включает проверку на null

2022-12-19 14:21 UTC, Tiozafrem commented on web/Controllers/RoomController.cs
> +            if (ModelState.IsValid)
В данном вариации id берётся из запроса. Это не лучшая идея, нельзя позволять пользователю выбирать себе id

2022-12-19 14:21 UTC, Tiozafrem commented on web/Controllers/RoomController.cs
> +    public async Task<IActionResult> RoomDetails([FromBody] Room room)
Если мы создаём комнату, то почему сразу не привязать туда этого же пользователя

2023-02-07 21:36 UTC, merged