Feature/category
SoftBox-CPS/BackendMVC pull request #20
Opened 2023-03-04 16:47 UTC by Zenobiam

2023-04-29 14:56 UTC, Zenobiam commented
???

2023-06-11 11:26 UTC, CrlnProgramming requested changes

2023-06-11 11:26 UTC, CrlnProgramming commented on web/Controllers/CategoryController.cs
>      protected override Task<bool> AccessAdd()
Cool

2023-06-11 11:27 UTC, CrlnProgramming approved these changes

2023-06-11 11:29 UTC, Tiozafrem approved these changes

2023-06-11 11:30 UTC, merged