Feature/user org
SoftBox-CPS/BackendMVC pull request #21
Opened 2023-05-20 11:03 UTC by Zenobiam

Метод обновления пользователя организации выдает ошибку в actionResult, но работает исправно

2023-08-06 14:57 UTC, CrlnProgramming commented
Это актуалбный реквест? Половина функционала уже реализовано

2023-10-19 15:48 UTC, Tiozafrem requested changes

2023-10-19 15:48 UTC, Tiozafrem commented on web/Properties/serviceDependencies.local.json
> +{
Зачем это тут?

2023-10-19 15:48 UTC, Tiozafrem commented on SoftBox.DataBase/Repository/UserOrganizationRepository.cs
> +        return user.OrganizationId == organizationId ? true : false;
Тернарка тут зачем? Можно же просто вернуть результат сравнения.

2023-10-19 15:48 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +        var userId = Guid.Parse(User.Claims.First(x => x.Type == "id").Value);
В конструкторе мы уже не так делаем

2023-11-10 17:36 UTC, Tiozafrem approved these changes

2023-11-10 17:36 UTC, Tiozafrem commented on SoftBox.DataBase/Repository/UserOrganizationRepository.cs
> +        var user = await db.UserOrganizations.FirstOrDefaultAsync(x => x.UserId == userId);
А что вернётся если пользователь без организации?

2023-11-10 17:36 UTC, Tiozafrem commented on SoftBox.DataBase/Repository/UserOrganizationRepository.cs
> +        var user = await db.UserOrganizations.FirstOrDefaultAsync(x => x.UserId == userId);
Если у нас уже есть метод для получения id организации, то почему его не использовать?

2023-11-10 17:36 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +    private bool is_userOrg;
что за _?

2023-11-11 11:07 UTC, merged