added hotFix for (Category, Organization, Product, User)Controllers.
SoftBox-CPS/BackendMVC pull request #24
Opened 2023-08-30 22:49 UTC by CrlnProgramming

added on ctor contextAccessor and Connection string =)
little bit remarks with AuthorizeAttribute

2023-08-31 10:36 UTC, Tiozafrem requested changes
Обсуждалось же ещё что надо изменить контроллер для чата, а его нет.

2023-08-31 10:36 UTC, Tiozafrem commented on web/appsettings.Development.json
> +  },
Этот файл точно надо трогать?

2023-08-31 10:36 UTC, Tiozafrem commented on web/Controllers/CategoryController.cs
> +[Authorize]
Точно надо на все контроллеры добавлять этот атрибут? Если да, то для обычных get запросов надо добавить противоположный атрибут, это почти везде нужно.

2023-08-31 10:36 UTC, Tiozafrem commented on web/Controllers/CategoryController.cs
> +        var userId = Guid.Parse(this.contextAccessor.HttpContext.User.Claims.First(x => x.Type == "id").Value);
А зачем здесь эта переменная, если она нигде не используется?

2023-08-31 10:36 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +        var userId = Guid.Parse(this.contextAccessor.HttpContext.User.Claims.First(x => x.Type == "id").Value);
В этом контроллере эта информация нужна, только почему это не присвоено полю? И не во всех местах в этом контроллере заменено обращение

2023-08-31 10:36 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +        var userId = Guid.Parse(this.contextAccessor.HttpContext.User.Claims.First(x => x.Type == "id").Value);
В этом контроллере не везде заменено

2023-08-31 10:37 UTC, CrlnProgramming commented on web/Controllers/CategoryController.cs
> +        var userId = Guid.Parse(this.contextAccessor.HttpContext.User.Claims.First(x => x.Type == "id").Value);
Что бы потом обращаться. 
Хорошо, я исправлю. 
Спасибо

2023-08-31 10:38 UTC, CrlnProgramming commented on web/Controllers/ProductController.cs
> +        var userId = Guid.Parse(this.contextAccessor.HttpContext.User.Claims.First(x => x.Type == "id").Value);
да, поправлю. 
Спасибо.

2023-08-31 10:38 UTC, CrlnProgramming commented on web/Controllers/OrganizationController.cs
> +        var userId = Guid.Parse(this.contextAccessor.HttpContext.User.Claims.First(x => x.Type == "id").Value);
Хорошо, поправлю. 
Спасибо.

2023-08-31 17:06 UTC, Zenobiam commented
В UserOrganization Controller будем в другом коммите добавлять, на котором вчера пофиксили?

2023-08-31 17:14 UTC, Zenobiam approved these changes
В UserOrganization Controller будем в другом коммите добавлять, на котором вчера пофиксили?

2023-08-31 20:20 UTC, Tiozafrem requested changes

2023-08-31 20:20 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +[Authorize]
Так как обычный не зарегистрированный пользователь сможет посмотреть товар? Просто человек из сети.

2023-08-31 20:20 UTC, Tiozafrem commented on web/Controllers/OrganizationController.cs
> +        var _ = await AccessGet();
Что? Зачем?

2023-08-31 20:20 UTC, Tiozafrem commented on web/Controllers/ChatController.cs
> +            new Guid((this.userId).ToString()),
Зачем тут такое преобразование? Достаточно тут просто оставить userId

2023-08-31 20:20 UTC, Tiozafrem commented on web/Controllers/CategoryController.cs
> +    protected override async Task<bool> AccessDelete(int id)
Такой метод точно нужен? Он не сломает базовый контроллер?

2023-09-01 10:04 UTC, Zenobiam commented on web/Controllers/OrganizationController.cs
> +        this.userType = userRepository.GetTypeUserByIdAsync(userId).Result;
а точно ли нужен глобальный тип пользователя? Тут получается что никакой пользователь кроме админа и модератора не может создать свою организацию

2023-09-01 10:06 UTC, Zenobiam commented on web/Controllers/OrganizationController.cs
> +            return Task.Run(() => false);
точно ли нужен глобальный тип пользователя? Тут получается что никакой пользователь кроме админа и модератора не может создать свою организацию

2023-09-01 10:07 UTC, Zenobiam commented on web/Controllers/OrganizationController.cs
>      }
точно ли нужен глобальный тип пользователя? Тут получается что никакой пользователь кроме админа и модератора не может создать свою организацию

2023-09-07 15:39 UTC, CrlnProgramming reviewed
update all commentaries

2023-09-09 12:25 UTC, Tiozafrem approved these changes

2023-09-09 12:26 UTC, merged