Room list v.0.1
SoftBox-CPS/BackendMVC pull request #8
Opened 2022-08-04 19:12 UTC by CrlnProgramming

Обещанный пул реквест. Реализация Producta, подготовка к реализации RoomList_a

TODO: нужен общий хаб для рума куда будет входить чат.

2022-08-05 12:18 UTC, Tiozafrem requested changes
Требуются доработки.

2022-08-05 12:18 UTC, Tiozafrem commented on web/Views/Product/Create.cshtml
> +        <input asp-for="ProductCategories" class="form-control" />
Данный метод работает? Он же должен выбирать из списка категории.

2022-08-05 12:18 UTC, Tiozafrem commented on web/Views/Product/AllProducts.cshtml
> +        @foreach(var obj in Model)
Obj плохой стиль. Хотя бы item,  а лучше просто product.

2022-08-05 12:18 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +            var faund = await productRepository.GetByName(organizationName);
Как пишется поиск на английском? И по смыслу это не поиск, а найденные продукты.

2022-08-05 12:18 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +            if (product.Id.ToString() == product.Name)
Какой смысл этой проверки? Если продукт только создаётся, у него id пустой.

2022-08-05 12:18 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +            return RedirectToAction("Index");
В индексе есть место для вывода сообщений о ошибке?

2022-08-05 12:18 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +            if (ModelState.IsValid)
Условие верное? Получается что при не валидном состояние модели он всегда вернёт View или OK.

2022-08-05 12:18 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +            var obj = await productRepository.Update(product);
Что хранит в себе эта переменная? По названию вообще не понятно.

2022-08-05 12:18 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +    public async Task<IActionResult> Delete(Guid id)
Зачем делать метод удаления? Он есть в базовом классе.

2022-08-05 12:18 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +            var obj = await productRepository.GetById(id);
Что в себе хранит эта переменная?

2022-08-05 12:18 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +            return View(obj);
Какое тут View возвращаешь? Удалённого уже объекта?

2022-08-05 12:18 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +    public async Task<IActionResult> Create(Product product)
Где в данном методе идёт связь продукта и организации? Во View она нигде не передаётся.

2022-08-05 12:18 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +    [HttpGet]
Для Api лучше указывать полный путь, иначе не получиться составить документацию. Актуально для всех методов в контроллере.

2022-08-05 16:05 UTC, CrlnProgramming commented on web/MVCWebApplication.csproj
> +  <ItemGroup>
Выпелил, хз автоматический создалось

2022-08-06 07:56 UTC, CrlnProgramming commented on SoftBox.DataBase/Repository/RoomRepository.cs
> +    public async Task<Room> AddRoom(Room roomItem, CancellationToken cancel = default)
Он потом будет доделываться со своими надстройками

2022-08-06 07:59 UTC, CrlnProgramming commented on web/Views/Product/AllProducts.cshtml
> +        @foreach(var obj in Model)
Готово

2022-08-06 08:01 UTC, CrlnProgramming commented on web/Controllers/ProductController.cs
> +            var faund = await productRepository.GetByName(organizationName);
Готово

2022-08-06 08:04 UTC, CrlnProgramming commented on web/Controllers/ProductController.cs
> +    [HttpGet]
ActionName ты имеешь ввиду?

2022-08-06 09:02 UTC, CrlnProgramming commented on web/Controllers/ProductController.cs
> +            return View(obj);
return RedirectToAction("Index") ?

2022-08-06 09:02 UTC, CrlnProgramming commented on web/Controllers/ProductController.cs
> +            return View(obj);
или в 404?

2022-08-06 09:52 UTC, CrlnProgramming commented on web/Controllers/ProductController.cs
> +    public async Task<IActionResult> Create(Product product)
Она на уровне создания модели, разве нет?

2022-08-06 09:54 UTC, CrlnProgramming commented on web/Controllers/ProductController.cs
> +            var obj = await productRepository.GetById(id);
Продукт который надо удалить

2022-08-06 09:55 UTC, CrlnProgramming commented on web/Controllers/ProductController.cs
> +            return RedirectToAction("Index");
Пока нету, это в основном для логов

2022-08-06 09:55 UTC, CrlnProgramming commented on web/Controllers/ProductController.cs
> +            if (ModelState.IsValid)
ну получается пока так

2022-08-06 09:56 UTC, CrlnProgramming commented on web/Controllers/ProductController.cs
> +            var obj = await productRepository.Update(product);
Поменял

2022-08-09 08:07 UTC, Tiozafrem approved these changes
Весь добавленный функционал точно рабочий?

2022-08-09 08:07 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +    public async Task<IActionResult> Create(Product product)
Нет. У тебя как передается объект в репозиторий, так и создаться. Репозиторий ничего не должен знать о запросе. Обработчик запроса должен вставить в объект связь с организацией. А этот метод и есть обработчик запросов.

2022-08-09 08:07 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +            if (ModelState.IsValid)
Если так то это надо исправить

2022-08-09 08:07 UTC, Tiozafrem commented on web/Controllers/ProductController.cs
> +            return RedirectToAction("Index");
Если этого сейчас нет,  то зачем это нужно сейчас? У нас остальные контроллеры без этого сделаны. Это надо вводить уже сейчас или пока выкинуть это.

2022-08-09 08:07 UTC, Tiozafrem commented on web/appsettings.json
> +    "SoftBoxMS": "Data Source=(localdb)\\MSSQLLocalDB;Database=SoftboxDB;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnet
Зачем каждый раз переписывать бд под себя?

2022-08-09 08:07 UTC, Tiozafrem commented on SoftBox.DataBase/Migrations/20220805182610_Initial.cs
> +﻿using Microsoft.EntityFrameworkCore.Migrations;
Зачем тут нужна эта миграция? Она пустая.

2022-08-09 08:07 UTC, Tiozafrem commented on SoftBox.DataBase/Migrations/20220805182610_Initial.Designer.cs
> +﻿// <auto-generated />
Зачем тут нужна эта миграция?

2022-08-09 08:08 UTC, Tiozafrem requested changes

2022-08-09 08:08 UTC, Tiozafrem commented on SoftBox.DataBase/InterfacesRepository/IProductRepository.cs
> +    // public Task<GetPrefered>(int count)
Что это за возвращаемый тип?

2022-08-19 09:29 UTC, closed without merging